export const PLANTA_CONFIG = {
  dimensionesPlanta: { ancho: 3.2, largo: 3.1, areaTotalM2: 9.92 },
  equipos: [
    {
      id: "horno",
      nombre: "Horno Doble Camara Pizza (70x85 cm)",
      tipo: "HORNO",
      dimensiones: "70 cm x 85 cm",
      combustible: "Gas Propano (GLP con pipeta)",
      camaras: 2,
      capacidadBandejas60x40: 2,
      capacidadTartasVascas: 8,
      capacidadCroissants: 24,
      tiempoCalentamientoMin: 20,
      costoHoraGasCOP: 2200,
      potenciaGas: "35.000 BTU/h",
      temperaturaRango: "50°C - 350°C",
      cuelloDeBotellaDesc: "Capacidad de horneado limitada a 2 niveles refractarios simultaneos.",
      cadCoords: { x: "14%", y: "12%", w: "26%", h: "28%" }
    },
    {
      id: "batidora",
      nombre: "Batidora Planetaria 6 Litros",
      tipo: "BATIDORA",
      dimensiones: "Pedestal (45 x 35 cm)",
      capacidadBowlLitros: 6,
      capacidadMasaBatidaKg: 4.0,
      capacidadMasaPesadaKg: 2.2,
      potenciaElectrica: "800 W / 110V",
      tiempoCicloMin: 18,
      cuelloDeBotellaDesc: "Maximo 4 tartas vascas o 2 tortas por tanda de batido de 6L.",
      cadCoords: { x: "75%", y: "56%", w: "18%", h: "22%" }
    },
    {
      id: "nevera",
      nombre: "Nevera Vertical (70x70 cm)",
      tipo: "REFRIGERACION",
      dimensiones: "70 cm x 70 cm",
      capacidadLitros: 420,
      temperaturaRango: "0°C - 5°C",
      capacidadTartasOreo: 16,
      capacidadBandejasFermentacion: 4,
      cuelloDeBotellaDesc: "Espacio critico para reposo de hojaldres y asentar tartas horneadas.",
      cadCoords: { x: "72%", y: "12%", w: "22%", h: "24%" }
    },
    {
      id: "meson_central",
      nombre: "Meson Central de Trabajo (80x110 cm)",
      tipo: "AREA_PREPARACION",
      dimensiones: "80 cm x 110 cm (0.88 m2)",
      material: "Acero Inox AISI 304",
      operariosMax: 2,
      usos: "Pesaje, amasado fino, laminado, porcionado y decorado.",
      cuelloDeBotellaDesc: "Area util para 1 maestro pastelero o 2 en coordinacion estrecha.",
      cadCoords: { x: "42%", y: "38%", w: "23%", h: "33%" }
    },
    {
      id: "almacen_aux",
      nombre: "Almacenamiento / Superficie Auxiliar (2 Pocetas)",
      tipo: "LAVADO_ALMACEN",
      dimensiones: "180 cm x 50 cm",
      usos: "Lavado BPM, desinfeccion de insumos y enfriamiento inicial.",
      cadCoords: { x: "40%", y: "12%", w: "32%", h: "16%" }
    },
    {
      id: "estanteria",
      nombre: "Estanteria de Secos e Insumos",
      tipo: "ALMACEN_SECOS",
      dimensiones: "35 cm x 90 cm",
      usos: "Harinas de fuerza, azucares, frutos secos, moldes y empaques.",
      cadCoords: { x: "14%", y: "48%", w: "14%", h: "24%" }
    },
    {
      id: "pipeta",
      nombre: "Pipeta de Gas GLP (40 lb)",
      tipo: "ENERGIA",
      dimensiones: "35 x 35 cm",
      usos: "Alimentacion autonoma de gas para horno pizza.",
      cadCoords: { x: "16%", y: "38%", w: "16%", h: "10%" }
    }
  ],
  productos: [
    {
      id: "tarta-basca",
      nombre: "Tarta Basca (Basque Cheesecake)",
      categoria: "REPOSTERIA",
      precioVentaCOP: 15000,
      costoMateriaPrimaCOP: 4300,
      costoEmpaqueCOP: 700,
      tiempoHorneadoMin: 38,
      temperaturaHornoC: 220,
      tiempoEnfriadoMin: 90,
      unidadesPorHorneada: 8,
      unidadesPorBatido: 4,
      tiempoBatidoMin: 15,
      mermaPorcentaje: 0.05,
      foto: "https://lh3.googleusercontent.com/d/1Az_n0fWrBcwbB2CAtjD0l0Gfp0Dyz6ke=w1000-h1000",
      descripcion: "Tarta de queso cremosa tradicional estilo Donostia con superficie caramelizada.",
      cuelloBotellaPrincipal: "Horno y Enfriamiento en Nevera",
      pesoGramo: 900,
      demandaEstimadaDia: 24
    },
    {
      id: "croissant-queso",
      nombre: "Croissant de Queso",
      categoria: "PANADERIA",
      precioVentaCOP: 8000,
      costoMateriaPrimaCOP: 2200,
      costoEmpaqueCOP: 300,
      tiempoHorneadoMin: 18,
      temperaturaHornoC: 190,
      tiempoEnfriadoMin: 20,
      unidadesPorHorneada: 24,
      unidadesPorBatido: 30,
      tiempoBatidoMin: 25,
      mermaPorcentaje: 0.04,
      foto: "https://gmothqjjqvbxshvvlbrq.supabase.co/storage/v1/object/public/Images_eventos/menu_print_images/1777576887346.jpg",
      descripcion: "Masa hojaldrada crujiente de fermentacion lenta rellena de queso fundente.",
      cuelloBotellaPrincipal: "Laminado en Meson y Fermentacion",
      pesoGramo: 100,
      demandaEstimadaDia: 45
    },
    {
      id: "rollo-canela",
      nombre: "Rollo de Canela",
      categoria: "PANADERIA",
      precioVentaCOP: 8500,
      costoMateriaPrimaCOP: 2100,
      costoEmpaqueCOP: 400,
      tiempoHorneadoMin: 22,
      temperaturaHornoC: 180,
      tiempoEnfriadoMin: 15,
      unidadesPorHorneada: 24,
      unidadesPorBatido: 24,
      tiempoBatidoMin: 20,
      mermaPorcentaje: 0.03,
      foto: "https://drive.google.com/thumbnail?id=14vp7k3GN0Ja4TEGy_wlfXUIHRxznYABB&sz=w1000-h1000",
      descripcion: "Masa brioche esponjosa aromatizada con canela ceylan y glaseado suave de queso crema.",
      cuelloBotellaPrincipal: "Meson de Enrollado y Fermentacion",
      pesoGramo: 120,
      demandaEstimadaDia: 40
    },
    {
      id: "torta-zanahoria",
      nombre: "Torta de Zanahoria",
      categoria: "REPOSTERIA",
      precioVentaCOP: 15000,
      costoMateriaPrimaCOP: 4100,
      costoEmpaqueCOP: 700,
      tiempoHorneadoMin: 45,
      temperaturaHornoC: 175,
      tiempoEnfriadoMin: 60,
      unidadesPorHorneada: 8,
      unidadesPorBatido: 4,
      tiempoBatidoMin: 20,
      mermaPorcentaje: 0.04,
      foto: "https://gmothqjjqvbxshvvlbrq.supabase.co/storage/v1/object/public/Images_eventos/menu_print_images/1777577079443.jpg",
      descripcion: "Bizcocho humedo de zanahoria fresca con nueces tostadas y frosting cremoso.",
      cuelloBotellaPrincipal: "Tiempo de Horneado (45 min)",
      pesoGramo: 850,
      demandaEstimadaDia: 18
    },
    {
      id: "torta-chocolate",
      nombre: "Torta de Chocolate",
      categoria: "REPOSTERIA",
      precioVentaCOP: 16000,
      costoMateriaPrimaCOP: 4800,
      costoEmpaqueCOP: 700,
      tiempoHorneadoMin: 40,
      temperaturaHornoC: 180,
      tiempoEnfriadoMin: 60,
      unidadesPorHorneada: 8,
      unidadesPorBatido: 4,
      tiempoBatidoMin: 20,
      mermaPorcentaje: 0.04,
      foto: "https://lh3.googleusercontent.com/d/1Az_n0fWrBcwbB2CAtjD0l0Gfp0Dyz6ke=w1000-h1000",
      descripcion: "Tres texturas de chocolate intenso 58% con fudge artesanal.",
      cuelloBotellaPrincipal: "Batidora 6L y Horneado",
      pesoGramo: 900,
      demandaEstimadaDia: 20
    },
    {
      id: "croissant-jamon-queso",
      nombre: "Croissant Jamon y Queso",
      categoria: "PANADERIA",
      precioVentaCOP: 12500,
      costoMateriaPrimaCOP: 3600,
      costoEmpaqueCOP: 400,
      tiempoHorneadoMin: 18,
      temperaturaHornoC: 190,
      tiempoEnfriadoMin: 15,
      unidadesPorHorneada: 24,
      unidadesPorBatido: 30,
      tiempoBatidoMin: 25,
      mermaPorcentaje: 0.03,
      foto: "https://gmothqjjqvbxshvvlbrq.supabase.co/storage/v1/object/public/Images_eventos/menu_print_images/1777576887346.jpg",
      descripcion: "Hojaldre artesanal de mantequilla relleno de jamon seleccionado y queso fundido.",
      cuelloBotellaPrincipal: "Laminado en Meson Central",
      pesoGramo: 130,
      demandaEstimadaDia: 35
    },
    {
      id: "palito-queso",
      nombre: "Palito de Queso",
      categoria: "PANADERIA",
      precioVentaCOP: 8000,
      costoMateriaPrimaCOP: 2300,
      costoEmpaqueCOP: 300,
      tiempoHorneadoMin: 20,
      temperaturaHornoC: 195,
      tiempoEnfriadoMin: 15,
      unidadesPorHorneada: 30,
      unidadesPorBatido: 45,
      tiempoBatidoMin: 20,
      mermaPorcentaje: 0.02,
      foto: "https://drive.google.com/thumbnail?id=13bozO9EXdWgndtpKKBYv5mIbhe5qUDO2&sz=w1000-h1000",
      descripcion: "Hojaldrado tradicional con abundante queso costeño artesanal tostado al horno.",
      cuelloBotellaPrincipal: "Armado Manual en Meson",
      pesoGramo: 110,
      demandaEstimadaDia: 50
    },
    {
      id: "pie-manzana",
      nombre: "Pie de Manzana",
      categoria: "REPOSTERIA",
      precioVentaCOP: 16000,
      costoMateriaPrimaCOP: 4500,
      costoEmpaqueCOP: 700,
      tiempoHorneadoMin: 45,
      temperaturaHornoC: 180,
      tiempoEnfriadoMin: 50,
      unidadesPorHorneada: 8,
      unidadesPorBatido: 6,
      tiempoBatidoMin: 20,
      mermaPorcentaje: 0.05,
      foto: "https://drive.google.com/thumbnail?id=1Az6kUgHQb4qMKXnPBBSDYqVCBB1kzrPt&sz=w1000-h1000",
      descripcion: "Masa quebrada crocante con manzanas caramelizadas a fuego lento, nuez moscada y canela.",
      cuelloBotellaPrincipal: "Tiempo de Horneado y Coccion de Relleno",
      pesoGramo: 800,
      demandaEstimadaDia: 15
    },
    {
      id: "torta-banano-caramelo",
      nombre: "Torta de Banano, Mani y Caramelo",
      categoria: "REPOSTERIA",
      precioVentaCOP: 12000,
      costoMateriaPrimaCOP: 3200,
      costoEmpaqueCOP: 600,
      tiempoHorneadoMin: 40,
      temperaturaHornoC: 175,
      tiempoEnfriadoMin: 40,
      unidadesPorHorneada: 8,
      unidadesPorBatido: 4,
      tiempoBatidoMin: 18,
      mermaPorcentaje: 0.04,
      foto: "https://drive.google.com/thumbnail?id=153U_H5x5NfnQybSlbyRxt9ALG_J2YkD5&sz=w1000-h1000",
      descripcion: "Bizcocho denso de banano maduro con toffee suave de mantequilla y crocante de mani.",
      cuelloBotellaPrincipal: "Batidora 6L (Volumen denso)",
      pesoGramo: 750,
      demandaEstimadaDia: 16
    },
    {
      id: "brioche-90g",
      nombre: "Pan Brioche Artesanal 90g",
      categoria: "PANADERIA",
      precioVentaCOP: 6500,
      costoMateriaPrimaCOP: 1400,
      costoEmpaqueCOP: 300,
      tiempoHorneadoMin: 15,
      temperaturaHornoC: 185,
      tiempoEnfriadoMin: 20,
      unidadesPorHorneada: 30,
      unidadesPorBatido: 25,
      tiempoBatidoMin: 22,
      mermaPorcentaje: 0.03,
      foto: "https://drive.google.com/thumbnail?id=12BTi-KVzIyHeg7oKG3s6qI5HGUShkGQw&sz=w1000-h1000",
      descripcion: "Pan frances enriquecido con mantequilla pura al 20%, miga sedosa y dorada con yema de huevo.",
      cuelloBotellaPrincipal: "Fermentacion Final y Amasado",
      pesoGramo: 90,
      demandaEstimadaDia: 40
    }
  ],
  costosFijosBase: {
    arriendo10m2: 1200000,
    nominaPanaderoPastelero: 2200000,
    gasPropanoPipetas: 350000,
    electricidadComercial: 450000,
    mantenimientoAseoBPM: 300000,
    depreciacionEquiposCAD: 350000
  }
};
