/**
 * AGENDA TABLE STRUCTURE
 * 
 * Table name in Supabase: "Agenda"
 * 
 * This table stores event information for the cafe's event calendar system.
 */

export const AgendaTableStructure = {
  tableName: "Agenda",
  
  fields: {
    // Primary Key (UUID generated by crearItem action)
    _id: {
      type: "UUID",
      required: true,
      description: "Unique identifier for the event"
    },
    
    // Event Basic Information
    nombreES: {
      type: "TEXT",
      required: true,
      description: "Name of the event"
    },
    
    fecha: {
      type: "DATE",
      required: true,
      description: "Event date (YYYY-MM-DD format)"
    },
    
    horaInicio: {
      type: "TIME",
      required: true,
      description: "Start time of the event (HH:MM format)"
    },
    
    horaFinal: {
      type: "TIME",
      required: true,
      description: "End time of the event (HH:MM format)"
    },
    
    // Client Information
    nombreCliente: {
      type: "TEXT",
      required: false,
      description: "Name of the client/organizer"
    },
    
    emailCliente: {
      type: "TEXT",
      required: false,
      description: "Client email address"
    },
    
    telefonoCliente: {
      type: "TEXT",
      required: false,
      description: "Client phone number"
    },
    
    // Event Details
    numeroPersonas: {
      type: "INTEGER",
      required: false,
      default: 1,
      description: "Expected number of attendees"
    },
    
    valor: {
      type: "TEXT",
      required: false,
      description: "Event price (e.g., '$50,000' or 'Gratis')"
    },
    
    autores: {
      type: "TEXT",
      required: false,
      description: "Event authors/organizers"
    },
    
    infoAdicional: {
      type: "TEXT",
      required: false,
      description: "Additional information about the event"
    },
    
    // Media
    bannerIMG: {
      type: "TEXT (URL)",
      required: false,
      description: "URL of the event banner image"
    },
    
    linkInscripcion: {
      type: "TEXT (URL)",
      required: false,
      description: "Registration/inscription link"
    },
    
    // Services (JSON field)
    servicios: {
      type: "JSONB",
      required: false,
      description: "Services requested for the event (JSON stringified)",
      structure: {
        alimentos: {
          activo: "BOOLEAN",
          descripcion: "TEXT - Food service requirements"
        },
        mesas: {
          activo: "BOOLEAN",
          descripcion: "TEXT - Table and chair requirements"
        },
        audioVisual: {
          activo: "BOOLEAN",
          descripcion: "TEXT - Audio/visual equipment needs"
        },
        otros: {
          activo: "BOOLEAN",
          descripcion: "TEXT - Other service requirements"
        }
      }
    }
  },
  
  // Example record
  exampleRecord: {
    _id: "550e8400-e29b-41d4-a716-446655440000",
    nombreES: "Lanzamiento de Libro",
    fecha: "2025-02-15",
    horaInicio: "18:00",
    horaFinal: "21:00",
    nombreCliente: "María González",
    emailCliente: "maria@example.com",
    telefonoCliente: "300-123-4567",
    numeroPersonas: 50,
    valor: "$100,000",
    autores: "María González, Juan Pérez",
    infoAdicional: "Presentación de libro de poesía con vino y aperitivos",
    bannerIMG: "https://example.com/banner.jpg",
    linkInscripcion: "https://eventbrite.com/evento123",
    servicios: JSON.stringify({
      alimentos: {
        activo: true,
        descripcion: "Vino, quesos y aperitivos para 50 personas"
      },
      mesas: {
        activo: true,
        descripcion: "Necesitamos 10 mesas redondas en el área principal"
      },
      audioVisual: {
        activo: true,
        descripcion: "Micrófono inalámbrico y proyector para presentación"
      },
      otros: {
        activo: false,
        descripcion: ""
      }
    })
  },
  
  // SQL to create table (for reference)
  createTableSQL: `
    CREATE TABLE "Agenda" (
      "_id" UUID PRIMARY KEY,
      "nombreES" TEXT NOT NULL,
      "fecha" DATE NOT NULL,
      "horaInicio" TIME NOT NULL,
      "horaFinal" TIME NOT NULL,
      "nombreCliente" TEXT,
      "emailCliente" TEXT,
      "telefonoCliente" TEXT,
      "numeroPersonas" INTEGER DEFAULT 1,
      "valor" TEXT,
      "autores" TEXT,
      "infoAdicional" TEXT,
      "bannerIMG" TEXT,
      "linkInscripcion" TEXT,
      "servicios" JSONB,
      "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Create indexes for better query performance
    CREATE INDEX idx_agenda_fecha ON "Agenda"("fecha");
    CREATE INDEX idx_agenda_nombreCliente ON "Agenda"("nombreCliente");
  `
};

export default AgendaTableStructure;
